### ISSUE TITLE
Add the deployed link on the ReadME

### ISSUE THREAD

**Issue by DonaldTsang** [MobButcher/KinkList#3]
This is good to be viewed https://mobbutcher.github.io/KinkList/

**Comment by MobButcher** [comment]
Oh, yes, thanks! I'll quickly patch this up now.

**Comment by MobButcher** [comment]
Fixed by [this commit](https://github.com/MobButcher/KinkList/commit/1a103008a46d2febd495b26759253668ccf66775).
